### PR TITLE
fixed string formatting errors

### PR DESCRIPTION
**Pull request by hedin-hiervard**
Prevented the logger to work in Godot 3.1.alpha1

### CODE REVIEW

**Comment by mitchcurtis** [comment]
So is this project dead? Should I use your repo instead, @hedin-hiervard?

I get a bunch of errors after setting this to autoload (which seem to be fixed with your patches):

>  res://3rdparty/logger/logger.gd:382 - Parse Error: Too many arguments for 'warn()' call. Expected at most 2.
>  modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
>  Script does not inherit a Node: res://3rdparty/logger/logger.gd
>  editor/editor_autoload_settings.cpp:448 - Condition ' !info->node ' is true. Continuing..:
> Add AutoLoad
>  res://3rdparty/logger/logger.gd:382 - Parse Error: Too many arguments for 'warn()' call. Expected at most 2.
>  modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
>

**Comment by hedin-hiervard** [comment]
Feel free to use and contribute. I use this
fork for my game Dwarven Skykeep.

**Comment by akien-mga** [comment]
The first two commits look good, but the rest should go in separate PRs, as they're unrelated to fixing string formatting.

The third commit also breaks compatibility by changing the names of the logging levels in a seemingly arbitrary manner, so this would need discussion.

**Comment by SirMoM** [comment]
I think this can be closed since the errors of this PR are already resolved in #8.

**Comment by akien-mga** [comment]
Closing as superseded by later PRs. Thanks for the contribution!
